# Generated by Django 3.1 on 2020-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroidService', '0002_auto_20200818_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='matrix',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asteroidsighting',
            name='device_matrix',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
