# Generated by Django 3.1 on 2020-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroidService', '0003_auto_20200818_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='matrix',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='asteroidsighting',
            name='device_matrix',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
